version: '3.8'

# 定义自定义网络
networks:
  app-network:
    driver: bridge

services:
  redis:
    image: registry.cn-hangzhou.aliyuncs.com/wzh-library/redis:5.0.8
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-network
    restart: unless-stopped
    command: [ '-- requirepass frog', '-- appendonly yes' ]

  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/wzh-library/mysql:5.7.32 
    container_name: mysql
    ports:
      - 3306:3306
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: frog
      MYSQL_DATABASE: frog_agriculture
    command:
      [
        'mysqld',
        '--character-set-server=utf8',
        '--collation-server=utf8_unicode_ci',
        '--default-time-zone=+8:00',
        '--lower-case-table-names=1',
        '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION',
        '--max_allowed_packet=256M',
        '--innodb_buffer_pool_size=256M',
        '--innodb_log_file_size=128M'
      ]     

  emqx:
    image: registry.cn-hangzhou.aliyuncs.com/wzh-library/emqx:5.6.1
    container_name: emqx
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8883:8883
      - 8084:8084
      - 18083:18083
    privileged: true
    networks:
      - app-network
    restart: unless-stopped
    #volumes:
      #- ./emqx/conf/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
      #- ./emqx/conf/emqx_web_hook.conf:/opt/emqx/etc/plugins/emqx_web_hook.conf
    environment:
      EMQX_ALLOW__ANONYMOUS: "false"
      SET_CONTAINER_TIMEZONE: "true"
      CONTAINER_TIMEZONE: Asia/Shanghai

  java:
    image: registry.cn-hangzhou.aliyuncs.com/wzh-library/openjdk:8-jdk-ubuntu-18.04.2
    container_name: java
    ports:
      - 8080:8080
      - 5061:5061/udp
      - 5005:5005
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./java/frog-admin.jar:/server.jar
      - ./java/application-prod.yml:/application-prod.yml
    environment:
      TZ: Asia/Shanghai
    command: java -jar /server.jar --spring.config.location=file:/application-prod.yml

  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/wzh-library/nginx:1.22.0
    container_name: nginx
    ports:
      - 8090:80
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

